"""Cab section: the mic catalog and the IR-stripping encoding."""

from __future__ import annotations

import pytest

from format.parser import parse, parse_file
from format.structured import build, set_parameter
from format.writer import write
from packs.loader import PackError, list_packs, load_pack
from packs.paths import EXAMPLES_DIR, all_presets

# The one preset committed to the repo: generated by this project, IR-free, so
# it works on a fresh clone. The user's own presets live in their data
# directory and are picked up automatically when present.
EXAMPLE_PRESET = EXAMPLES_DIR / "Example_Clean_PR12.xml"


@pytest.fixture(scope="module")
def pack():
    return load_pack("morgan")


@pytest.fixture(scope="module")
def mics(pack):
    """The internal-mic catalog, straight from the manifest."""
    spec = pack.require("cabParameters", "leftMicType")
    assert spec.members, "the mic catalog should be declared as enum members"
    return [spec.members[str(i)] for i in range(len(spec.members))]


def test_catalog_matches_confirmed_indices(mics):
    """The two indices confirmed against real presets must match the catalog."""
    assert mics[0] == "Dynamic 57"
    assert mics[8] == "Ribbon 121"
    assert len(mics) == 11


def test_custom_ir_is_the_last_catalog_entry(mics, pack):
    """Index 10 is not a mic: it switches the cab over to the custom IR file.

    The catalog stopped at 9 for a long time, which made a legitimate value
    unwritable and left a preset that uses an IR unreadable. Confirmed in the
    plugin's own dropdown — ten internal mics, then a separate CUSTOM IR
    section — and by writing 10 and reading the label back."""
    assert mics[10] == "Custom IR"
    for key in ("leftMicType", "rightMicType"):
        spec = pack.require("cabParameters", key)
        assert pack.to_stored(spec, "Custom IR") == "10"
        # 11 is past the end; the plugin discards it rather than clamping.
        with pytest.raises(PackError, match="not a valid selector"):
            pack.to_stored(spec, 11)


def test_both_close_mic_selectors_share_one_catalog(pack):
    """The two close mics draw from the same list, so they must share the table —
    a divergence here would mean two sources of truth."""
    tables = [
        pack.require("cabParameters", k).members
        for k in ("leftMicType", "rightMicType")
    ]
    assert all(t == tables[0] for t in tables)


def test_room_mics_are_a_different_control(pack):
    """The room mics were assumed to share the close-mic catalog. They do not:
    the plugin accepts only 0-2 there and rewrites anything higher to 0, so a
    shared table would have made 'Ribbon 121' a silent no-op.

    They also have no control in the plugin UI at all — the cab page offers two
    mics and a Room Send level, nothing more — and the Audio Unit exposes them
    as reserved slots named R3/R6. The note has to say so, or someone will spend
    an afternoon looking for a control that isn't there. Verified in the UI and
    against the Audio Unit — see docs/measuring-against-the-plugin.md."""
    for key in ("leftRoomMicType", "rightRoomMicType"):
        spec = pack.require("cabParameters", key)
        assert spec.members is None, (
            f"{key} must not be pointed at a mic catalog it does not use"
        )
        assert spec.needs_confirmation
        assert "NO CONTROL FOR THIS EXISTS" in spec.note


def test_mic_selection_by_name_is_case_insensitive(pack):
    spec = pack.require("cabParameters", "leftMicType")
    assert pack.to_stored(spec, "ribbon 121") == "8"
    assert pack.to_stored(spec, "  DYNAMIC 57  ") == "0"


def test_every_mic_name_round_trips(pack, mics):
    spec = pack.require("cabParameters", "leftMicType")
    for i, name in enumerate(mics):
        assert pack.to_stored(spec, name) == str(i)
        assert spec.member_name(str(i)) == name


def test_presets_use_known_mic_indices(pack):
    """Every close-mic value in every preset we can see resolves to a real mic,
    and every room-mic value is one the plugin actually accepts."""
    for preset_path in all_presets(list_packs()):
        preset = build(parse_file(str(preset_path)))
        for param in preset.parameters:
            if not param.key.endswith("MicType"):
                continue
            spec = pack.get(param.module_path, param.key)
            if spec is None:
                continue
            if spec.members is None:  # room mics: names unread, bounds measured
                assert 0 <= int(float(param.value)) <= 2, (
                    f"{preset_path.name} {param.key}={param.value} is outside the "
                    f"0-2 the plugin accepts"
                )
                continue
            assert spec.member_name(param.value) is not None, (
                f"{preset_path.name} {param.key}={param.value} is not in the catalog"
            )


def test_set_mic_by_index_via_writer():
    """Setting a mic index keeps the file valid and reads back correctly."""
    preset = build(parse_file(str(EXAMPLE_PRESET)))
    set_parameter(preset, "cabParameters", "leftMicType", "9")  # Ribbon 160
    reparsed = build(parse(write(preset.tokens)))
    assert reparsed.by_path[("cabParameters", "leftMicType")].value == "9"


def test_strip_irs_matches_the_ir_free_encoding():
    """Clearing a custom IR must reproduce, byte for byte, how an IR-free preset
    stores that field.

    Previously this needed two of the user's own presets and skipped on a fresh
    clone. It no longer does: the IR fields are addressable even when empty, so
    an IR-using preset can be synthesised from the bundled IR-free one and
    stripped back, which is a stronger check anyway — the round trip must land
    on the original bytes exactly.
    """
    original = EXAMPLE_PRESET.read_bytes()

    with_ir = build(parse(original))
    for side in ("left", "right"):
        set_parameter(
            with_ir,
            "cabParameters",
            f"{side}ChosenIRFilePath",
            f"/Users/someone/IRs/{side}-cab.wav",
        )
    ir_bytes = write(with_ir.tokens)
    assert ir_bytes != original, "the synthesised preset should carry IR paths"

    reparsed = build(parse(ir_bytes))
    assert (
        reparsed.by_path[("cabParameters", "leftChosenIRFilePath")].value
        == "/Users/someone/IRs/left-cab.wav"
    )

    stripped = build(parse(ir_bytes))
    for side in ("left", "right"):
        set_parameter(stripped, "cabParameters", f"{side}ChosenIRFilePath", "")

    assert write(stripped.tokens) == original, (
        "stripping an IR must restore the exact bytes of the IR-free encoding"
    )


def test_stripping_preserves_every_other_parameter():
    """--strip-irs must change the IR fields and nothing else."""
    before = build(parse_file(str(EXAMPLE_PRESET)))
    preset = build(parse_file(str(EXAMPLE_PRESET)))
    set_parameter(
        preset, "cabParameters", "leftChosenIRFilePath", "/tmp/x.wav"
    )
    after = build(parse(write(preset.tokens)))

    assert len(after.parameters) == len(before.parameters)
    differing = {
        key
        for key, param in after.by_path.items()
        if before.by_path[key].value != param.value
    }
    assert differing == {("cabParameters", "leftChosenIRFilePath")}


def test_strip_irs_also_moves_the_mic_off_custom_ir():
    """Clearing the IR path is only half the job.

    The mic selector is what decides whether the cab plays a modelled mic or the
    file. A preset that uses an IR holds it at index 10, "Custom IR". Clearing
    only the path leaves the plugin showing `Custom IR / No File` — a preset
    that is worse than the one we started with, and silently so.
    """
    from scripts.apply_spec import strip_custom_irs

    preset = build(parse_file(str(EXAMPLE_PRESET)))
    for side in ("left", "right"):
        set_parameter(preset, "cabParameters", f"{side}ChosenIRFilePath",
                      f"/Users/someone/IRs/{side}.wav")
        set_parameter(preset, "cabParameters", f"{side}MicType", "10")

    changed = dict(strip_custom_irs(preset))
    assert "leftMicType" in changed and "rightMicType" in changed

    after = build(parse(write(preset.tokens)))
    for side, expected in (("left", "0"), ("right", "4")):
        assert after.by_path[("cabParameters", f"{side}ChosenIRFilePath")].value == ""
        assert after.by_path[("cabParameters", f"{side}MicType")].value == expected, (
            f"{side} cab still points at the custom IR that was just removed"
        )


def test_strip_irs_leaves_a_real_mic_alone():
    """Only a selector actually pointing at the file may be moved."""
    from scripts.apply_spec import strip_custom_irs

    preset = build(parse_file(str(EXAMPLE_PRESET)))
    before = preset.by_path[("cabParameters", "leftMicType")].value
    set_parameter(preset, "cabParameters", "leftChosenIRFilePath", "/tmp/x.wav")
    strip_custom_irs(preset)
    assert preset.by_path[("cabParameters", "leftMicType")].value == before
