"""Cab section: the mic catalog and the IR-stripping encoding."""

from __future__ import annotations

import pathlib

import pytest

from format.parser import parse, parse_file
from format.structured import build, set_parameter
from format.writer import write
from packs.loader import list_packs, load_pack
from packs.paths import EXAMPLES_DIR, all_presets

# The one preset committed to the repo: generated by this project, IR-free, so
# it works on a fresh clone. The user's own presets live in their data
# directory and are picked up automatically when present.
EXAMPLE_PRESET = EXAMPLES_DIR / "Example_Clean_PR12.xml"


@pytest.fixture(scope="module")
def pack():
    return load_pack("morgan")


@pytest.fixture(scope="module")
def mics(pack):
    """The internal-mic catalog, straight from the manifest."""
    spec = pack.require("cabParameters", "leftMicType")
    assert spec.members, "the mic catalog should be declared as enum members"
    return [spec.members[str(i)] for i in range(len(spec.members))]


def test_catalog_matches_confirmed_indices(mics):
    """The two indices confirmed against real presets must match the catalog."""
    assert mics[0] == "Dynamic 57"
    assert mics[8] == "Ribbon 121"
    assert len(mics) == 10


def test_all_four_mic_selectors_share_one_catalog(pack):
    """Cab and room mics draw from the same list, so they must share the table —
    a divergence here would mean two sources of truth."""
    keys = ["leftMicType", "rightMicType", "leftRoomMicType", "rightRoomMicType"]
    tables = [pack.require("cabParameters", k).members for k in keys]
    assert all(t == tables[0] for t in tables)


def test_mic_selection_by_name_is_case_insensitive(pack):
    spec = pack.require("cabParameters", "leftMicType")
    assert pack.to_stored(spec, "ribbon 121") == "8"
    assert pack.to_stored(spec, "  DYNAMIC 57  ") == "0"


def test_every_mic_name_round_trips(pack, mics):
    spec = pack.require("cabParameters", "leftMicType")
    for i, name in enumerate(mics):
        assert pack.to_stored(spec, name) == str(i)
        assert spec.member_name(str(i)) == name


def test_presets_use_known_mic_indices(pack):
    """Every *MicType value in every preset we can see resolves to a real mic."""
    for preset_path in all_presets(list_packs()):
        preset = build(parse_file(str(preset_path)))
        for param in preset.parameters:
            if not param.key.endswith("MicType"):
                continue
            spec = pack.get(param.module_path, param.key)
            if spec is None:
                continue
            assert spec.member_name(param.value) is not None, (
                f"{preset_path.name} {param.key}={param.value} is not in the catalog"
            )


def test_set_mic_by_index_via_writer():
    """Setting a mic index keeps the file valid and reads back correctly."""
    preset = build(parse_file(str(EXAMPLE_PRESET)))
    set_parameter(preset, "cabParameters", "leftMicType", "9")  # Ribbon 160
    reparsed = build(parse(write(preset.tokens)))
    assert reparsed.by_path[("cabParameters", "leftMicType")].value == "9"


def test_strip_irs_matches_factory_default_encoding():
    """Stripping a custom IR (set path to "") must produce byte-identical
    encoding to an IR-free preset's empty-IR field, and the mic selection
    must survive.

    Needs two of the user's own presets: an IR-free reference and an IR-using
    one. Neither ships with the repo, so this skips on a fresh clone — the
    encoding it pins is exercised at runtime by apply_spec.py --strip-irs.
    """
    library = {p.name: p for p in all_presets(list_packs())}
    default, soft = library.get("Default.xml"), library.get("Soft_Touch.xml")
    if default is None or soft is None:
        pytest.skip("Default.xml / Soft_Touch.xml not present (bring your own presets)")

    preset = build(parse_file(str(soft)))
    for side in ("left", "right"):
        key = f"{side}ChosenIRFilePath"
        if ("cabParameters", key) in preset.by_path:
            set_parameter(preset, "cabParameters", key, "")
    out = write(preset.tokens)

    def region(data: bytes, kw: bytes) -> bytes:
        i = data.find(kw)
        return data[i : i + len(kw) + 5]

    default_bytes = default.read_bytes()
    for kw in (b"leftChosenIRFilePath", b"rightChosenIRFilePath"):
        assert region(out, kw) == region(default_bytes, kw), (
            f"stripped {kw!r} encoding differs from factory Default"
        )

    # After strip + reparse, the IR keys are absent (internal-mic mode) and the
    # mic selection is preserved.
    rp = build(parse(out))
    for side in ("left", "right"):
        assert ("cabParameters", f"{side}ChosenIRFilePath") not in rp.by_path
    assert rp.by_path[("cabParameters", "leftMicType")].value == "0"
    assert rp.by_path[("cabParameters", "rightMicType")].value == "8"
