"""Cab mic catalog + named-mic selection."""

from __future__ import annotations

import pathlib

import pytest

from format.parser import parse, parse_file
from format.structured import build
from format.writer import write
from schema.cab import load_mics, mic_index_to_name, mic_name_to_index

SAMPLES_DIR = pathlib.Path(__file__).parent.parent / "samples"

# The one preset committed to the repo: generated by this project, IR-free, so
# it works on a fresh clone. Other presets in samples/ are the user's own and
# are git-ignored.
EXAMPLE_PRESET = SAMPLES_DIR / "Example_Clean_PR12.xml"


def test_catalog_matches_confirmed_indices():
    """The two indices confirmed against real presets must match the catalog."""
    assert mic_index_to_name(0) == "Dynamic 57"
    assert mic_index_to_name(8) == "Ribbon 121"
    assert len(load_mics()) == 10


def test_name_to_index_roundtrip():
    for i, name in enumerate(load_mics()):
        assert mic_name_to_index(name) == i
        assert mic_index_to_name(i) == name


def test_name_lookup_is_case_insensitive():
    assert mic_name_to_index("ribbon 121") == 8
    assert mic_name_to_index("  DYNAMIC 57  ") == 0


def test_unknown_mic_raises():
    with pytest.raises(KeyError):
        mic_name_to_index("Sennheiser 666")


def test_samples_use_known_mic_indices():
    """Every *MicType value in every sample should resolve to a real mic."""
    for sample in sorted(SAMPLES_DIR.glob("*.xml")):
        preset = build(parse_file(str(sample)))
        for p in preset.parameters:
            if p.key.endswith("MicType"):
                idx = int(float(p.value))
                assert mic_index_to_name(idx) is not None, (
                    f"{sample.name} {p.key}={idx} not in catalog"
                )


def test_set_mic_by_index_via_writer():
    """Setting a mic index keeps the file valid and reads back correctly."""
    from format.structured import set_parameter

    preset = build(parse_file(str(EXAMPLE_PRESET)))
    set_parameter(preset, "cabParameters", "leftMicType", "9")  # Ribbon 160
    reparsed = build(parse(write(preset.tokens)))
    assert reparsed.by_path[("cabParameters", "leftMicType")].value == "9"
    assert mic_index_to_name(9) == "Ribbon 160"


def test_strip_irs_matches_factory_default_encoding():
    """Stripping a custom IR (set path to "") must produce byte-identical
    encoding to an IR-free preset's empty-IR field, and the mic selection
    must survive.

    Needs two of the user's own presets: an IR-free reference and an
    IR-using one. Neither ships with the repo, so this skips on a fresh
    clone — the encoding it pins is exercised at runtime by
    apply_spec.py --strip-irs.
    """
    from format.structured import set_parameter

    default = (SAMPLES_DIR / "Default.xml")
    soft = (SAMPLES_DIR / "Soft_Touch.xml")
    for p in (default, soft):
        if not p.exists():
            pytest.skip(f"{p.name} not present (bring your own presets)")

    preset = build(parse_file(str(soft)))
    for side in ("left", "right"):
        key = f"{side}ChosenIRFilePath"
        if ("cabParameters", key) in preset.by_path:
            set_parameter(preset, "cabParameters", key, "")
    out = write(preset.tokens)

    def region(data: bytes, kw: bytes) -> bytes:
        i = data.find(kw)
        return data[i : i + len(kw) + 5]

    default_bytes = default.read_bytes()
    for kw in (b"leftChosenIRFilePath", b"rightChosenIRFilePath"):
        assert region(out, kw) == region(default_bytes, kw), (
            f"stripped {kw!r} encoding differs from factory Default"
        )

    # After strip + reparse, the IR keys are absent (factory-mic mode) and
    # the mic selection is preserved.
    rp = build(parse(out))
    for side in ("left", "right"):
        assert ("cabParameters", f"{side}ChosenIRFilePath") not in rp.by_path
    assert rp.by_path[("cabParameters", "leftMicType")].value == "0"
    assert rp.by_path[("cabParameters", "rightMicType")].value == "8"
